plugin(ocp-aws-zone): fix api group; review safe guards

diff --git a/labs/oc-plugins/oc-aws_zone b/labs/oc-plugins/oc-aws_zone
--- a/labs/oc-plugins/oc-aws_zone
+++ b/labs/oc-plugins/oc-aws_zone
@@ -9,22 +9,42 @@ set -o pipefail
 set -o nounset
 set -o errexit
 
-# ##################
-# Dependencies Check
-# ##################
-
-
-
 # ####################
 # Install dependencies
 # ####################
 
+check_clients() {
+    export NEED_BIN_CLIENTS=false
+    BIN_INSTALLER="${CLIENT_INSTALLER:-./openshift-install}"
+    BIN_OC="${CLIENT_OC:-./oc}"
+    if [[ ! -x "${BIN_INSTALLER}" ]] || [[ ! -x "${BIN_OC}" ]]; then
+        NEED_BIN_CLIENTS=true
+    fi
+}
+
+preflight_install() {
+    if [[ -z "${PULL_SECRET_FILE:-}" ]]; then
+        echo "#> ERROR: Environment variable is not set: PULL_SECRET_FILE
+# It's used to extract the clients and create the install-config.yaml
+# Example:
+export PULL_SECRET_FILE=\${HOME}/.openshift/pull-secret-latest.json"
+        exit 1
+    fi
+}
+
 cmd_install_clients() {
     echo "#INFO: Starting install_clients"
-    preflight_create
+    preflight_install
     check_clients
     if [[ ${NEED_BIN_CLIENTS} != true ]]; then
         return
+    fi
+
+    if [[ -z "${VERSION:-}" ]]; then
+        echo "#> ERROR: Environment variable is not set: VERSION
+# Example:
+export VERSION=4.11.0"
+        exit 1
     fi
 
     local image="quay.io/openshift-release-dev/ocp-release:${VERSION}-x86_64"
@@ -36,6 +56,10 @@ cmd_install_clients() {
     tar xvfz "openshift-client-linux-${VERSION}.tar.gz"
     tar xvfz "openshift-install-linux-${VERSION}.tar.gz"
 }
+
+# ##################
+# Dependencies Check
+# ##################
 
 cmd_preflight_net_stack() {
     # Check subnet opt-in status
@@ -66,8 +90,10 @@ aws ec2 modify-availability-zone-group \
     fi
 }
 
-# oc
-# aws-cli
+
+# #############
+# cmd=preflight
+# #############
 cmd_prefilght() {
     if [[ ! -x "$(command -v oc)" ]]; then
         echo "#> ERROR: oc client is not found on your system (PATH). Please install it"
@@ -90,57 +116,41 @@ export CLUSTER_REGION=us-east-1"
 export ZONE_GROUP_NAME=${CLUSTER_REGION}-nyc-1a"
         exit 1
     fi
-}
-
-preflight_create() {
-    if [[ -z "${PULL_SECRET_FILE:-}" ]]; then
-        echo "#> ERROR: Environment variable is not set: PULL_SECRET_FILE
-# It's used to extract the clients and create the install-config.yaml
-# Example:
-export PULL_SECRET_FILE=\${HOME}/.openshift/pull-secret-latest.json"
-        exit 1
-    fi
-    if [[ -z "${SSH_PUB_KEY_FILE:-}" ]]; then
-        echo "#> ERROR: Environment variable is not set: SSH_PUB_KEY_FILE
-# It's used to extract the clients and create the install-config.yaml
-# Example:
-export SSH_PUB_KEY_FILE=\${HOME}/.ssh/id_rsa.pub"
-        exit 1
-    fi
-}
-
-check_clients() {
-    export NEED_BIN_CLIENTS=false
-    BIN_INSTALLER="${CLIENT_INSTALLER:-./openshift-install}"
-    BIN_OC="${CLIENT_OC:-./oc}"
-    if [[ ! -x "${BIN_INSTALLER}" ]] || [[ ! -x "${BIN_OC}" ]]; then
-        NEED_BIN_CLIENTS=true
-        if [[ -z "${VERSION:-}" ]]; then
-            echo "#> ERROR: Environment variable is not set: VERSION
-    # Example:
-    export VERSION=4.11.0"
-            exit 1
-        fi
-    fi
-}
-
-
-check_dep_cluster_info() {
     if [[ -z "${CLUSTER_NAME:-}" ]]; then
-        echo "#> ERROR: Environment variable is not set: CLUSTER_NAME
+    echo "#> ERROR: Environment variable is not set: CLUSTER_NAME
+# Example:
 export CLUSTER_NAME=lzdemo"
         exit 1
     fi
 }
 
+check_dep_install_config() {
+    if [[ -z "${SSH_PUB_KEY_FILE:-}" ]]; then
+        echo "#> ERROR: Environment variable is not set: SSH_PUB_KEY_FILE
+# It's used on install-config.yaml
+# Example:
+export SSH_PUB_KEY_FILE=\${HOME}/.ssh/id_rsa.pub"
+        exit 1
+    fi
+    if [[ -z "${BASE_DOMAIN:-}" ]]; then
+        echo "#> ERROR: Environment variable is not set: BASE_DOMAIN
+# It's used to extract the clients and create the install-config.yaml
+# Example:
+export BASE_DOMAIN=\"devcluster.example.com\""
+        exit 1
+    fi
+}
+
+# ########################
+# cmd_stack_vpc_create
+# ########################
 check_dep_create_vpc() {
     cmd_preflight_net_stack
     if [[ -z "${VPC_CIDR:-}" ]]; then
-        echo "#> ERROR: Environment variable is not set: CLUSTER_NAME
+        echo "#> ERROR: Environment variable is not set: VPC_CIDR
 export VPC_CIDR=\"10.0.0.0/16\""
         exit 1
     fi
-    
 }
 
 set_vars_stack_net() {
@@ -148,10 +158,21 @@ set_vars_stack_net() {
     export STACK_VPC=${CLUSTER_NAME}-vpc
 }
 
-set_vars_stack_zone() {
-    set_vars_stack_net
-    export ZONE_GROUP_SHORTNAME=${ZONE_GROUP_NAME/${CLUSTER_REGION}-/}
-    export STACK_ZONE="${CLUSTER_NAME}-zone-${ZONE_GROUP_SHORTNAME}"
+stack_wait_for_complete() {
+    local stack_name=$1
+    local stack_status
+    echo -e " > Start waiter for the stack [${stack_name}] to report as CREATE_COMPLETE..."
+    while true; do
+        stack_status=$(aws cloudformation describe-stacks \
+            --stack-name "${stack_name}" \
+            | jq -r '.Stacks[0].StackStatus' )
+        if [[ ${stack_status} == "CREATE_COMPLETE" ]]; then
+            echo " >> Stack report ${stack_status}, continuing...";
+            return
+        fi
+        echo " >> Stack reported undesired status: [${stack_status}] != [CREATE_COMPLETE]. Waiting 15s to the next check...";
+        sleep 15
+    done
 }
 
 create_net_stack_vpc() {
@@ -201,33 +222,10 @@ cmd_stack_vpc_create() {
     create_net_stack_vpc
 }
 
-cmd_stack_wait_complete() {
-    local stack_name=$1
-    local stack_status
-    echo -e " > Start waiter for the stack [${stack_name}] to report as CREATE_COMPLETE..."
-    while true; do
-        stack_status=$(aws cloudformation describe-stacks \
-            --stack-name "${stack_name}" \
-            | jq -r '.Stacks[0].StackStatus' )
-        if [[ ${stack_status} == "CREATE_COMPLETE" ]]; then
-            echo " >> Stack report ${stack_status}, continuing...";
-            return
-        fi 
-        echo " >> Stack reported undesired status: [${stack_status}] != [CREATE_COMPLETE]. Waiting 15s to the next check...";
-        sleep 15
-    done
-}
-
 cmd_stack_vpc_wait() {
     check_dep_create_vpc
-    cmd_stack_wait_complete "${STACK_VPC}"
+    stack_wait_for_complete "${STACK_VPC}"
 }
-
-cmd_stack_zone_wait() {
-    check_dep_create_vpc
-    cmd_stack_wait_complete "${STACK_ZONE}"
-}
-
 
 cmd_stack_vpc_check() {
     set_vars_stack_net
@@ -239,14 +237,27 @@ cmd_stack_vpc_delete() {
     aws cloudformation delete-stack --stack-name "${STACK_VPC}"
 }
 
-## Stack Zone
+# ##############
+# cmd_stack_zone
+# ##############
 check_dep_create_zone() {
     cmd_preflight_net_stack
-    if [[ -z "${VPC_CIDR:-}" ]]; then
-        echo "#> ERROR: Environment variable is not set: CLUSTER_NAME
-export VPC_CIDR=\"10.0.0.0/16\""
+    if [[ -z "${ZONE_CIDR:-}" ]]; then
+        echo "#> ERROR: Environment variable is not set: ZONE_CIDR
+export ZONE_CIDR=\"10.0.128.0/20\""
         exit 1
     fi
+    if [[ -z "${ZONE_GROUP_NAME:-}" ]]; then
+        echo "#> ERROR: Environment variable is not set: ZONE_GROUP_NAME
+export ZONE_GROUP_NAME=\"us-east-1-nyc-1a\""
+        exit 1
+    fi
+}
+
+set_vars_stack_zone() {
+    set_vars_stack_net
+    export ZONE_GROUP_SHORTNAME=${ZONE_GROUP_NAME/${CLUSTER_REGION}-/}
+    export STACK_ZONE="${CLUSTER_NAME}-zone-${ZONE_GROUP_SHORTNAME}"
 }
 
 create_net_stack_zone() {
@@ -316,6 +327,11 @@ EOF
         --parameters file://"${PWD}/${stack_net_var}"
 }
 
+cmd_stack_zone_wait() {
+    check_dep_create_vpc
+    stack_wait_for_complete "${STACK_ZONE}"
+}
+
 cmd_stack_zone_create() {
     check_dep_create_zone
     create_net_stack_zone
@@ -331,12 +347,14 @@ cmd_stack_zone_delete() {
     aws cloudformation delete-stack --stack-name "${STACK_ZONE}"
 }
 
-# install-config
-
+# ##################
+# cmd_install_config
+# ##################
 cmd_install_config() {
 
     local install_config
-    preflight_create
+    preflight_install
+    check_dep_install_config
     set_vars_stack_zone
     install_config="${PWD}/install-config.yaml"
 
@@ -385,6 +403,19 @@ EOF
     cp -v "${install_config}" "${PWD}"/install-config-copy.yaml
 }
 
+# #####################
+# cmd_install_manifests
+# #####################
+check_dep_install_manifests() {
+    if [[ -z "${ZONE_GROUP_NAME:-}" ]]; then
+        echo "#> ERROR: Environment variable is not set: SSH_PUB_KEY_FILE
+# It's used on install-config.yaml
+# Example:
+export SSH_PUB_KEY_FILE=\${HOME}/.ssh/id_rsa.pub"
+        exit 1
+    fi
+}
+
 cmd_install_manifests() {
 
     if [[ -z "${INSTANCE_TYPE:-}" ]]; then
@@ -404,6 +435,7 @@ export INSTANCE_TYPE=c5d.2xlarge"
     local subnet_id
     local manifest_machineset
     set_vars_stack_zone
+    check_dep_install_manifests
 
     echo "#> Creating installer manifests..."
     ${CLIENT_INSTALLER:-./openshift-install} create manifests  \
@@ -456,6 +488,7 @@ spec:
         machine.openshift.io/cluster-api-machine-type: edge
         machine.openshift.io/cluster-api-machineset: ${cluster_id}-edge-${ZONE_GROUP_NAME}
     spec:
+      lifecycleHooks: {}
       metadata:
         labels:
           location: local-zone
@@ -468,7 +501,7 @@ spec:
         value:
           ami:
             id: ${ami_id}
-          apiVersion: awsproviderconfig.openshift.io/v1beta1
+          apiVersion: machine.openshift.io/v1beta1
           blockDevices:
           - ebs:
               volumeSize: 120
@@ -497,8 +530,13 @@ spec:
           userDataSecret:
             name: worker-user-data
 EOF
+    echo "#> Show content of MachineSet manifest ${manifest_machineset}"
+    cat "${manifest_machineset}"
 }
 
+# ##########################
+# cmd_install_create_cluster
+# ##########################
 cmd_install_create_cluster() {
     ${CLIENT_INSTALLER:-./openshift-install} create cluster \
         --log-level="${INSTALL_LOGLEVEL:-info}" \
@@ -522,6 +560,9 @@ cmd_check_cluster() {
     ${CLIENT_OC:-./oc} get nodes -l location=local-zone
 }
 
+# ###########################
+# cmd_install_destroy_cluster
+# ###########################
 cmd_destroy_cluster() {
     set_vars_stack_zone
     echo "# Running Cluster destroy..."
@@ -543,7 +584,18 @@ cmd_destroy_all() {
     aws cloudformation delete-stack --stack-name "${STACK_VPC}"
 }
 
+# ##############
+# cmd_create_all
+# ##############
+check_dep_create_all() {
+    check_dep_create_vpc
+    check_dep_create_zone
+    preflight_install
+    check_dep_install_config
+}
+
 cmd_create_all() {
+    check_dep_create_all
     cmd_stack_vpc_create
     cmd_stack_vpc_wait
     cmd_stack_zone_create
@@ -553,6 +605,17 @@ cmd_create_all() {
     cmd_install_manifests
     cmd_install_create_cluster
     cmd_check_cluster
+}
+
+cmd_create_all_manifests() {
+    check_dep_create_all
+    cmd_stack_vpc_create
+    cmd_stack_vpc_wait
+    cmd_stack_zone_create
+    cmd_stack_zone_wait
+    cmd_install_clients
+    cmd_install_config
+    cmd_install_manifests
 }
 
 ##########
@@ -576,24 +639,25 @@ Available commands:
     "destroy-cluster"   : Destroy the OCP cluster
     "check-cluster"     : Check the existing OCP cluster
     "create-all"        : Create the VPC, Subnet on edge zone, then the OCP cluster in existing VPC approach
+    "create-manifests"  : Create the VPC, Subnet on edge zone, then the Installer manifests
 
 Available environment variables (ToDo description):
-    VERSION
-    CLIENT_OC
-    CLIENT_INSTALLER
-    INSTALL_LOGLEVEL
-    INSTALL_DIR
+    VERSION             : Target OCP Version to install the clients (oc and openshift-install)
+    CLIENT_OC           : Path of OC client to skip the install. Default: ./openshift-install
+    CLIENT_INSTALLER    : Path of openshift-install utility to skip the install. Default: ./openshift-install
+    INSTALL_LOGLEVEL    : Log level for openshift-install. Default: info
+    INSTALL_DIR         : Path of install dir. Default: ./
 
-    CLUSTER_NAME
-    CLUSTER_REGION
-    BASE_DOMAIN
-    SSH_PUB_KEY_FILE
-    PULL_SECRET_FILE
+    CLUSTER_NAME        : Cluster Name
+    CLUSTER_REGION      : AWS Region to install the cluster
+    BASE_DOMAIN         : BaseDomain used on install-config.yaml
+    SSH_PUB_KEY_FILE    : public SSH keys to be added to install-config.yaml
+    PULL_SECRET_FILE    : pull secret file to be used on install-config.yaml
 
-    INSTANCE_TYPE
-    ZONE_GROUP_NAME
-    ZONE_CIDR
-    VPC_CIDR
+    INSTANCE_TYPE       : Instance type used on MachineSet on the new zone
+    ZONE_GROUP_NAME     : Zone Group Name
+    VPC_CIDR            : VPC CIDR IP Block
+    ZONE_CIDR           : Subnet CIDR IP Block
 
 Examples:
     # Generic
@@ -648,6 +712,7 @@ main() {
         "check-cluster"     ) CMD="cmd_check_cluster" ;;
         "create-all"        ) CMD="cmd_create_all" ;;
         "destroy-all"       ) CMD="cmd_destroy_all" ;;
+        "create-manifests"  ) CMD="cmd_create_all_manifests" ;;
         *) helpme ;;
     esac
 
